language: python

python:
  - "3.6"
  - "3.8"

install:
  - pip install coveralls
  - pip install -r requirements.txt

script:
  - coverage run --source=messi setup.py test
  - make -s -C tst SANITIZE=yes
  - make -s -C examples

after_success:
  - coveralls
  - bash <(curl -s https://codecov.io/bash) -X coveragepy
